### ISSUE TITLE
DBAPI 2.0

### ISSUE THREAD

**Issue by tarekziade** [esnme/ultramysql#10]
Hello,

It would be interesting to support DBAPI 2.0 http://www.python.org/dev/peps/pep-0249/

That would facilitate ultramysql's integration as a driver into sqlalchemy for instance

**Comment by jskorpan** [comment]
That would be an obvious good idea. Sadly I'm not gonna be able to devote the time necessary to achieve that in the near future. I'd be happy to merge any pull requests with such changes.

One possibility could be to implement only the most necessary parts of a DBAPI 2.0 implementation in the C/C++ code and do the rest as a minimal Python wrapper.

**Comment by tarekziade** [comment]
Unfortunately I am not good enough in C++ to do this. I'll ask around ! :)

**Comment by hongqn** [comment]
I am writing a MySQLdb compatible wrapper for ultramysql, borrowing code from [PyMySQL](https://github.com/petehunt/PyMySQL) project.  It will be opensourced in several days.

**Comment by philipn** [comment]
@hongqn Any update on your status?  I'm very interested.

**Comment by shuxiang** [comment]
@hongqn Any update on your status? I'm very interested too.

**Comment by hongqn** [comment]
Here it is: https://github.com/hongqn/umysqldb

It is not used in production environment, yet.  Use at your own risk.
