### ISSUE TITLE
Native gevent support

### ISSUE THREAD

**Issue by vitaly-krugl** [esnme/ultramysql#13]
I would love to use ultramysql in my project, except for this one thing: "Compatible with gevent through monkey patching"; unfortunately, gevent's monkey-patching breaks some unsuspecting 3rd-party code.  After gevent.monkey.patch_all(), strange failures started to show up in Hbase-Thrift, for example.

Can there be an option in ultramysql to make it natively gevent-aware without monkey-patching?

Many thanks!

**Comment by jskorpan** [comment]
No that's not possible. Try monkey patching sockets only.

**Comment by mthurlin** [comment]
Isn't it enough to change:
sockmodule = PyImport_ImportModule ("socket");

to:
sockmodule = PyImport_ImportModule ("gevent.socket");

in io_python.c?

If so, then a simple change and recompile should do the trick for you @vitaly-krugl

**Comment by jskorpan** [comment]
Correct, a change that will not be merged into master how ever.

Den 7 mars 2012 09:20 skrev Markus Thurlin <
reply@reply.github.com

> :
> 
> Isn't it enough to change:
> sockmodule = PyImport_ImportModule ("socket");
> 
> to:
> sockmodule = PyImport_ImportModule ("gevent.socket");
> 
> in io_python.c?
> 
> If so, then a simple change and recompile should do the trick for you
> @vitaly-krugl
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/esnme/ultramysql/issues/13#issuecomment-4364088

## 

## 

Jonas Trnstrm
Product Manager
 e-mail: jonas.tarnstrom@esn.me
 skype: full name "Jonas Trnstrm"
 phone: +46 (0)734 231 552

ESN Social Software AB
www.esn.me

**Comment by vitaly-krugl** [comment]
> > No that's not possible. Try monkey patching sockets only.

Unfortunately, monkey-patching the socket was precisely what caused incompatibilities with other packages (e.g., DBUtils.PooledDB with pymysql).  Once we monkey-patch sockets, it affects all other packages in the process.

**Comment by vitaly-krugl** [comment]
I considered making my own changes (on my own branch) as recommended above and recompiling; my concern was that it might be more than just sockets in future releases.  It would be cool if there was a way to set concurrency policy (e.g., blocking, gevent, etc.). Thank you.
