### ISSUE TITLE
Python interpreter corruption

### ISSUE THREAD

**Issue by miracle2k** [esnme/ultramysql#14]
The module doesn't seem to play nice with Python:

```
import umysql
a.b = umysql.Connection()
```

gives me:

```
RuntimeError: Exception is set for no error in Connection_Destructor
```

What I would expect:

```
NameError: name 'a' is not defined
```

Even more strangely, there is this phenomenon:

I have also seen exceptions where the innermost entry of the stacktrace is missing.

**Comment by jskorpan** [comment]
Hi.
There might be some progress to this in another branch, one which changes I
havent come around to merge yet. Check it out at
https://github.com/hongqn/ultramysql

//JT

Den lördagen den 14:e april 2012 skrev Michael Elsdörfer:

> The module doesn't seem to play nice with Python:
> 
>    import umysql
>    a.b = umysql.Connection()
> 
> gives me:
> 
>    RuntimeError: Exception is set for no error in Connection_Destructor
> 
> What I would expect:
> 
>    NameError: name 'a' is not defined
> 
> Even more strangely, there is this phenomenon:
> 
> I have also seen exceptions where the innermost entry of the stacktrace is
> missing.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/esnme/ultramysql/issues/14

## 

## 

Jonas Tärnström
Product Manager
• e-mail: jonas.tarnstrom@esn.me
• skype: full name "Jonas Tärnström"
• phone: +46 (0)734 231 552

ESN Social Software AB
www.esn.me

**Comment by jskorpan** [comment]
Fixed in master
