### ISSUE TITLE
ultramysql throws not connected exception

### ISSUE THREAD

**Issue by ghost** [esnme/ultramysql#15]
ultramysql throws not connected exception

```
db = umysql.Connection()
db.connect(config.db_host, config.db_port, config.db_user, config.db_password, config.db_database)
...

def get_info():
    rs = db.query(sql)
RuntimeError: Not connected
<Greenlet at 0x1df6870: handle(<socket at 0x1e59390 fileno=[Errno 9] Bad file des, ('127.0.0.1', 64871))> failed with RuntimeError
```

How to make it KeepAlive forever?

**Comment by jskorpan** [comment]
After how long?

**Comment by ghost** [comment]
More than 12 hours.

If umysql could detect it's not connect, why it does not auto-reconnect?

For walk around this, I have to write sth likes

```
import umysql
import config

db = umysql.Connection()
db.connect(config.db_host, config.db_port, config.db_user, config.db_password, config.db_database)

def db_query(sql):
    global db
    if not db.is_connected():
        db = umysql.Connection()
        db.connect(config.db_host, config.db_port, config.db_user, config.db_password, config.db_database)

    return db.query(sql)
```

**Comment by jskorpan** [comment]
Keep-alive is a server-side option.

//JT

2012/5/15 Shuge Lee <
reply@reply.github.com

> More than 12 hours.
> 
> If umysql could detect it's not connect, why it does not auto-reconnect?
> 
> For walk around this, I have to write sth likes
> 
> ```
> import umysql
> import config
> 
> db = umysql.Connection()
> db.connect(config.db_host, config.db_port, config.db_user,
> config.db_password, config.db_database)
> 
> def db_query(sql):
>    global db
>    if not db.is_connected():
>         db = umysql.Connection()
>        db.connect(config.db_host, config.db_port, config.db_user,
> config.db_password, config.db_database)
> 
>     return db.query(sql)
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/esnme/ultramysql/issues/15#issuecomment-5710623

## 

## 

Jonas Tärnström
Product Manager
• e-mail: jonas.tarnstrom@esn.me
• skype: full name "Jonas Tärnström"
• phone: +46 (0)734 231 552

ESN Social Software AB
www.esn.me

**Comment by ghost** [comment]
Do you mean this
http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/index.html

How to config it?

**Comment by jskorpan** [comment]
No,
It's a MySQL server-side feature somehow, can't help anymore than that

//JT

2012/5/15 Shuge Lee <
reply@reply.github.com

> Do you mean this
> http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/index.html
> 
> How to config it?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/esnme/ultramysql/issues/15#issuecomment-5711183

## 

## 

Jonas Tärnström
Product Manager
• e-mail: jonas.tarnstrom@esn.me
• skype: full name "Jonas Tärnström"
• phone: +46 (0)734 231 552

ESN Social Software AB
www.esn.me

**Comment by V-E-O** [comment]
MySQL clients has this option to check the connection status and auto-reconnect.
http://dev.mysql.com/doc/refman/5.1/en/mysql-ping.html
If the connection is idle for a long while, it's good idea to Ping from client side, or we have to wrap umysql in another class to provide this auto-reconnect feature.
