### ISSUE TITLE
Socket receive buffer full

### ISSUE THREAD

**Issue by paulie4** [esnme/ultramysql#16]
I have a couple simple loops that calculate a bunch of values then try to insert them into MySQL, something like this:

``` python
for i in items:
    # compare i to every other item, returned as a dictionary
    calcedVals = calculateValues(items, i)
    for j in calcedVals:
        dbconn.query('INSERT INTO tableName VALUES (%s, %s, %s)' %
                     (i, j, calcedVals[j]))
```

where i and j are `INT`s in MySQL, and each calculated comparison is a `DOUBLE` in MySQL.

There are 11,396 items so it would be inserting about 11,396*11,395 (129,857,420) rows, but it only inserted 1,525,202 (it was on the 134th i and 9667th j).  Then umysql gave this error and essentially quit:

``` python
umysql.Error: (0, 'Socket receive buffer full')
```

Do you know what could have caused that?  Do you think I should just put a `try..except` around it, and just close and reopen the connection if that happens?  Although, I'm not sure if that will fix it, since I don't see any references to `m_reader` in `Connection::close()`.

Thanks,
Paulie

**Comment by jskorpan** [comment]
Sounds like a possible bug,
Could you create a minimal reproduction case as a test in tests.py and pull
request it?

//JT

2012/5/23 paulie4 <
reply@reply.github.com

> I have a couple simple loops that calculate a bunch of values then try to
> insert them into MySQL, something like this:
> 
> ``` python
> for i in items:
>    # compare i to every other item, returned as a dictionary
>    calcedVals = calculateValues(items, i)
>    for j in calcedVals:
>        dbconn.query('INSERT INTO tableName VALUES (%s, %s, %s)' %
>                     (i, j, calcedVals[j]))
> ```
> 
> where i and j are `INT`s in MySQL, and each calculated comparison is a
> `DOUBLE` in MySQL.
> 
> There are 11,396 items so it would be inserting about 11,396*11,395
> (129,857,420) rows, but it only inserted 1,525,202 (it was on the 134th i
> and 9667th j).  Then umysql gave this error and essentially quit:
> 
> ``` python
> umysql.Error: (0, 'Socket receive buffer full')
> ```
> 
> Do you know what could have caused that?  Do you think I should just put a
> `try..except` around it, and just close and reopen the connection if that
> happens?  Although, I'm not sure if that will fix it, since I don't see any
> references to `m_reader` in `Connection::close()`.
> 
> Thanks,
> Paulie
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/esnme/ultramysql/issues/16

## 

## 

Jonas Tärnström
Product Manager
• e-mail: jonas.tarnstrom@esn.me
• skype: full name "Jonas Tärnström"
• phone: +46 (0)734 231 552

ESN Social Software AB
www.esn.me

**Comment by paulie4** [comment]
I ran the `testMySQLClientManyInserts()` test twice, once with the `assertEquals()` and once without (i.e. just calling `cnn.query()` without asserting), since there is a comment in `testMySQLClient2()` that says, "we always need to read the result from the database."  Both times, it crashed after 1,525,200 inserts (cnti = 153 and cntj = 5200).

https://github.com/esnme/ultramysql/pull/17

**Comment by jskorpan** [comment]
Interesting, thanks for the effort.

I'll take a look at it shortly

//JT

2012/5/24 paulie4 <
reply@reply.github.com

> I ran the `testMySQLClientManyInserts()` test twice, once with the
> `assertEquals()` and once without (i.e. just calling `cnn.query()` without
> asserting), since there is a comment in `testMySQLClient2()` that says, "we
> always need to read the result from the database."  Both times, it crashed
> after 1,525,200 inserts (cnti = 153 and cntj = 5200).
> 
> https://github.com/esnme/ultramysql/pull/17
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/esnme/ultramysql/issues/16#issuecomment-5913904

## 

## 

Jonas Tärnström
Product Manager
• e-mail: jonas.tarnstrom@esn.me
• skype: full name "Jonas Tärnström"
• phone: +46 (0)734 231 552

ESN Social Software AB
www.esn.me

**Comment by happy15** [comment]
I also encounter similar problem.

I try to query 450000rows of data out of mysql.  But this error bumped out

**Comment by jskorpan** [comment]
I've manged to successfully reproduce and have now fixed this issue. Thanks for the help!
