### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [esnme/ultramysql#19]
I would like to point out that identifiers like "[`__UMCONNECTION_H___`](https://github.com/esnme/ultramysql/blob/a6d8a12d040da48724585186550f73ceb041810e/lib/Connection.h#L60)" and "[`__PACKETREADER_H__`](https://github.com/esnme/ultramysql/blob/a6d8a12d040da48724585186550f73ceb041810e/lib/PacketReader.h#L60)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming conventions of the C/C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jskorpan** [comment]
What part of the expected naming convention of the C/C++ language standard would that be in violation of?

**Comment by mthurlin** [comment]
ISO/IEC 14882-2003, Section 17.4.3.1.2 :)

**Comment by jskorpan** [comment]
Bastard : )

**Comment by elfring** [comment]
I recommend to delete [double underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#228797) from identifiers like include guards in the affected header files to make them a bit more standard-compliant.

**Comment by jskorpan** [comment]
Feel free to supply a pull request for this one, as of now since it's not an issue I'm not going to fix it.

Thanks!
