### ISSUE TITLE
Stored Procedures on amysql

### ISSUE THREAD

**Issue by jsia** [esnme/ultramysql#2]
I tried to call some stored procedures that returns recordset.  I'm getting errors I think it does not support stored procedure.  I currently use python mysqldb for calling stored procedures.  Are there some modifications that can be done to support stored procedure returns?

**Comment by jskorpan** [comment]
I'm unable to devote the time necessary to implement this.

I currently have no specification on how storage procedures works across the MySQL protocol. Sorry

**Comment by yihuang** [comment]
I believe this issue is fixed by my patch here: https://github.com/esnme/ultramysql/pull/26
