### ISSUE TITLE
Dict Cursor in ultraMySQL

### ISSUE THREAD

**Issue by pranjal5215** [esnme/ultramysql#22]
So here q.rows[0] gives a tuple.

How can I get results from dict cursor as in MySQL.

import umysql
cnn = umysql.Connection()
cnn.connect(DB_HOST, 3306, DB_USER, DB_PASSWD, DB_DB)
cnn.connect(DB_HOST, 3306, DB_USER, DB_PASSWD, DB_DB)
q = cnn.query("select \* from test_table")
q.rows[0]

(1,
 u'abc', 
 u'def',
 0,
 datetime.datetime(2013, 8, 13, 14, 25, 46),
 0,
 datetime.datetime(2012, 8, 13, 14, 26, 3),
 1)

**Comment by mthurlin** [comment]
You get the names in q.fields

**Comment by pranjal5215** [comment]
Right,

But it becomes cumbersome to each time get a field name from q.fields and
do a tuple indexing to q.rows

Rather it should be possible to pass a cursor object and get dicts from
executing the SQL query.

import MySQLdb.cursors as CursorClass
cnn.set_cursor(CursorClass.DictCursor)
q = cnn.query("select \* from test_table")

so we get results for the above query in this way :

({'id' : 1},
{'name' : u'abc'},
{'type' : u'def'},
{'sno' : 0},
{'startdate' : datetime.datetime(2013, 8, 13, 14, 25, 46)},
{'key' : 0},
{'modifiedon' : datetime.datetime(2012, 8, 13, 14, 26, 3)},
{'priority' : 1},

{'id' : 2},
{'name' : u'123'},
{'type' : u'456'},
{'sno' : 1},
{'startdate' : datetime.datetime(2013, 9, 13, 14, 25, 46)},
{'key' : 0},
{'modifiedon' : datetime.datetime(2012, 9, 13, 14, 26, 3)},
{'priority' : 1})

Actually, we need to use Gevent compatible MySQL library in our project and
we use Dict cursors over a lot of places.

If its possible to modify source to support dict cursors it would be very
useful. If we can agree on a format I can patch to support dict cursors.

On Thu, Sep 13, 2012 at 4:39 PM, Markus Thurlin notifications@github.comwrote:

> You get the names in q.fields
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/esnme/ultramysql/issues/22#issuecomment-8524928.

## 

Regards
Pranjal Pandit

Don't communicate by sharing memory; share memory by communicating.

**Comment by mthurlin** [comment]
A simple helper in your project could solve this easily:

```
def dict_cursor(q):
    for row in q.rows:
        yield dict(zip(q.fields, row))
```

**Comment by pranjal5215** [comment]
Yes Indeed, this can be done. But I was just wondering if this could be a
part of the project itself thereby increasing usability of the project.

In addition we also use redis. Has it been considered to develop
ultraredis. We also need async redis driver with gevent .

On Thu, Sep 13, 2012 at 5:28 PM, Markus Thurlin notifications@github.comwrote:

> A simple helper in your project could solve this easily:
> 
> def dict_cursor(q):
> for row in q.rows:
> yield dict(zip(q.fields, row))
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/esnme/ultramysql/issues/22#issuecomment-8525931.

## 

Regards
Pranjal Pandit

Don't communicate by sharing memory; share memory by communicating.

**Comment by jskorpan** [comment]
The next major version would definitely feature the Cursor object
