### ISSUE TITLE
Why not compatible with PEP 249?

### ISSUE THREAD

**Issue by zffl** [esnme/ultramysql#24]
I am very intrest in the greenlet support, but I look into the testcase, found the interface is total different with from now, so It's not very easy to transform from old driver to your driver. I hope you  can make it compatible with PEP 249. Then many people would choose this.

**Comment by jskorpan** [comment]
PEP 249 would be the next logical step in the development of UltraMySQL. Not sure how ever when I will be able to undertake it

//JT
