### ISSUE TITLE
Assert triggers if not all bytes can be sent at once

### ISSUE THREAD

**Issue by mthurlin** [esnme/ultramysql#41]
The number of bytes to send is calculated by:
`size_t bytesToSend = m_writer.getWriteCursor() - m_writer.getReadCursor();`
(at https://github.com/esnme/ultramysql/blob/master/lib/Connection.cpp#L173)

But, if not all bytes can be sent at once (slow connection and/or large payload), only the number of sent bytes will be passed to `m_writer.pull`.
(at https://github.com/esnme/ultramysql/blob/master/lib/Connection.cpp#L191)

However, `PacketWriter:pull` has the following assert:
`assert (m_writeCursor - m_readCursor <= cbSize);`
(at https://github.com/esnme/ultramysql/blob/master/lib/PacketWriter.cpp#L93)

Can this assert simply be removed? Or is there something else going on?

**Comment by jskorpan** [comment]
Pretty awesome problem you found there.
The assertion is just the sympthom. What will happen is that the simply not all data will be written. The Connection::writeSocket method needs to have a while loop forcing it to deliver all data or fail. It's the only way.

**Comment by jskorpan** [comment]
At closer look it appears only the assert is incorrect as writeSocket is called in loop until isDone condition is met from the sendPacket function in Connection
