### ISSUE TITLE
./python/umysql.h:81:3: error: expected specifier-qualifier-list before 'UINT8'

### ISSUE THREAD

**Issue by bbigras** [esnme/ultramysql#5]
Hi,

I'm unable to build `ultramysql`. Any idea?

```
C:\ultramysql>python setup.py build
running build
running build_ext
building 'umysql' extension
C:\mingw\bin\gcc.exe -mno-cygwin -mdll -O -Wall -DWIN32_LEAN_AND_MEAN -I./python -I./lib -IC:\Python27\include -IC:\Python27\PC -c ./python/umysql.c -o build\temp.win32-2.7\Release\.\python\umysql.o
In file included from ./python/umysql.c:60:0:
./python/umysql.h:81:3: error: expected specifier-qualifier-list before 'UINT8'
./python/umysql.c: In function 'API_resultSetField':
./python/umysql.c:150:3: error: 'UMTypeInfo' has no member named 'type'
./python/umysql.c: In function 'DecodeString':
./python/umysql.c:257:13: error: 'UMTypeInfo' has no member named 'charset'
./python/umysql.c:492:103: error: 'UMTypeInfo' has no member named 'charset'
./python/umysql.c: In function 'API_resultRowValue':
./python/umysql.c:511:15: error: 'UMTypeInfo' has no member named 'type'
./python/umysql.c:655:73: error: 'UMTypeInfo' has no member named 'type'
./python/umysql.c: At top level:
./python/umysql.c:679:3: warning: initialization from incompatible pointer type
./python/umysql.c: In function 'EscapeQueryArguments':
./python/umysql.c:1058:5: warning: implicit declaration of function '_alloca'
./python/umysql.c: At top level:
./python/umysql.c:1278:3: warning: initialization from incompatible pointer type
./python/umysql.c:1374:3: warning: initialization from incompatible pointer type
error: command 'gcc' failed with exit status 1
```

**Comment by jskorpan** [comment]
From the top of my head,

Try changing line 63 from
#include "mysqldefs.h"

to
#include <mysqldefs.h>

in
python/umysql.h

Please let me know what success you have with this. I haven't tried
building with mingw before only MSVC and gcc (on Linux)

//JT

Den 9 februari 2012 22:25 skrev Bruno Bigras <
reply@reply.github.com

> :
> 
> Hi,
> 
> I'm unable to build `ultramysql`. Any idea?
> 
>    C:\ultramysql>python setup.py build
>    running build
>    running build_ext
>    building 'umysql' extension
>    C:\mingw\bin\gcc.exe -mno-cygwin -mdll -O -Wall -DWIN32_LEAN_AND_MEAN
> -I./python -I./lib -IC:\Python27\include -IC:\Python27\PC -c
> ./python/umysql.c -o build\temp.win32-2.7\Release.\python\umysql.o
>    In file included from ./python/umysql.c:60:0:
>    ./python/umysql.h:81:3: error: expected specifier-qualifier-list before
> 'UINT8'
>    ./python/umysql.c: In function 'API_resultSetField':
>    ./python/umysql.c:150:3: error: 'UMTypeInfo' has no member named 'type'
>    ./python/umysql.c: In function 'DecodeString':
>    ./python/umysql.c:257:13: error: 'UMTypeInfo' has no member named
> 'charset'
>    ./python/umysql.c:492:103: error: 'UMTypeInfo' has no member named
> 'charset'
>    ./python/umysql.c: In function 'API_resultRowValue':
>    ./python/umysql.c:511:15: error: 'UMTypeInfo' has no member named 'type'
>    ./python/umysql.c:655:73: error: 'UMTypeInfo' has no member named 'type'
>    ./python/umysql.c: At top level:
>    ./python/umysql.c:679:3: warning: initialization from incompatible
> pointer type
>    ./python/umysql.c: In function 'EscapeQueryArguments':
>    ./python/umysql.c:1058:5: warning: implicit declaration of function
> '_alloca'
>    ./python/umysql.c: At top level:
>    ./python/umysql.c:1278:3: warning: initialization from incompatible
> pointer type
>    ./python/umysql.c:1374:3: warning: initialization from incompatible
> pointer type
>    error: command 'gcc' failed with exit status 1
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/esnme/ultramysql/issues/5

## 

## 

Jonas Trnstrm
Product Manager
 e-mail: jonas.tarnstrom@esn.me
 skype: full name "Jonas Trnstrm"
 phone: +46 (0)734 231 552

ESN Social Software AB
www.esn.me

**Comment by jskorpan** [comment]
Did this work?

Den 9 februari 2012 23:56 skrev Jonas Trnstrm <
jonas.tarnstrom@esportnetwork.com>:

> From the top of my head,
> 
> Try changing line 63 from
> #include "mysqldefs.h"
> 
> to
> #include <mysqldefs.h>
> 
> in
> python/umysql.h
> 
> Please let me know what success you have with this. I haven't tried
> building with mingw before only MSVC and gcc (on Linux)
> 
> //JT
> 
> Den 9 februari 2012 22:25 skrev Bruno Bigras <
> reply@reply.github.com
> 
> > :
> 
> Hi,
> 
> > I'm unable to build `ultramysql`. Any idea?
> > 
> >    C:\ultramysql>python setup.py build
> >    running build
> >    running build_ext
> >    building 'umysql' extension
> >    C:\mingw\bin\gcc.exe -mno-cygwin -mdll -O -Wall -DWIN32_LEAN_AND_MEAN
> > -I./python -I./lib -IC:\Python27\include -IC:\Python27\PC -c
> > ./python/umysql.c -o build\temp.win32-2.7\Release.\python\umysql.o
> >    In file included from ./python/umysql.c:60:0:
> >    ./python/umysql.h:81:3: error: expected specifier-qualifier-list
> > before 'UINT8'
> >    ./python/umysql.c: In function 'API_resultSetField':
> >    ./python/umysql.c:150:3: error: 'UMTypeInfo' has no member named 'type'
> >    ./python/umysql.c: In function 'DecodeString':
> >    ./python/umysql.c:257:13: error: 'UMTypeInfo' has no member named
> > 'charset'
> >    ./python/umysql.c:492:103: error: 'UMTypeInfo' has no member named
> > 'charset'
> >    ./python/umysql.c: In function 'API_resultRowValue':
> >    ./python/umysql.c:511:15: error: 'UMTypeInfo' has no member named
> > 'type'
> >    ./python/umysql.c:655:73: error: 'UMTypeInfo' has no member named
> > 'type'
> >    ./python/umysql.c: At top level:
> >    ./python/umysql.c:679:3: warning: initialization from incompatible
> > pointer type
> >    ./python/umysql.c: In function 'EscapeQueryArguments':
> >    ./python/umysql.c:1058:5: warning: implicit declaration of function
> > '_alloca'
> >    ./python/umysql.c: At top level:
> >    ./python/umysql.c:1278:3: warning: initialization from incompatible
> > pointer type
> >    ./python/umysql.c:1374:3: warning: initialization from incompatible
> > pointer type
> >    error: command 'gcc' failed with exit status 1
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/esnme/ultramysql/issues/5
> 
> ## 
> 
> ## 
> 
> Jonas Trnstrm
> Product Manager
>  e-mail: jonas.tarnstrom@esn.me
>  skype: full name "Jonas Trnstrm"
>  phone: +46 (0)734 231 552
> 
> ESN Social Software AB
> www.esn.me

## 

## 

Jonas Trnstrm
Product Manager
 e-mail: jonas.tarnstrom@esn.me
 skype: full name "Jonas Trnstrm"
 phone: +46 (0)734 231 552

ESN Social Software AB
www.esn.me

**Comment by bbigras** [comment]
No. I got the same error. :(
