### ISSUE TITLE
Lazy result fetching

### ISSUE THREAD

**Issue by smurfix** [esnme/ultramysql#6]
Right now ResultSet.rows contains the whole result. That's not a good idea, as I really need to process some large queries which doesn't fit in main memory and, even if it would fit, the latency would kill me. :-/

Ideally, ResultSet should be an iterator which fetches datasets as needed. For compatibility, the .rows would still be an array with the results; you can pre-fill it by way of a property.
Of course, that doesn't work as-is with nested queries, so the connection needs to keep a pointer to the last-returned resultset and tell it to fetch+store the rest of its data when the next query is started.

This is fairly straightforward to implement, I did it in ten minutes in the old gevent-mysql code.
See  github.com:smurfix/gevent-MySQL.git.

Looking at the ultramysql code, this would mean breaking up Connection::handleResultPacket(). If you create a new connection::readOneRow() instead, and call that from the resultset, that'd allow you to drop the m_capi.resultRowBegin/End() calls, so the whole thing would actually become (slightly) faster.

I hope to be able to get around to implementing that in a few weeks, I have a vacation coming up … if somebody beats me to it, good. ;-)

**Comment by jskorpan** [comment]
Hi,
Thanks for your interest in UltraMySQL.

I definitly see your use case. The obvious solution would be to mimic the
Cursor object used in other MySQL drivers (and in the official Python MySQL
database protocol for that matter).

When I implemented this driver the use case never was huge queries so
I cheapskate on it.

I'm sadly doubtful that I will have the time to implement in the near
future.
Good luck with your effort!

Den 10 februari 2012 22:08 skrev Matthias Urlichs <
reply@reply.github.com

> :
> 
> Right now ResultSet.rows contains the whole result. That's not a good
> idea, as I really need to process some large queries which doesn't fit in
> main memory and, even if it would fit, the latency would kill me. :-/
> 
> Ideally, ResultSet should be an iterator which fetches datasets as needed.
> For compatibility, the .rows would still be an array with the results; you
> can pre-fill it by way of a property.
> Of course, that doesn't work as-is with nested queries, so the connection
> needs to keep a pointer to the last-returned resultset and tell it to
> fetch+store the rest of its data when the next query is started.
> 
> This is fairly straightforward to implement, I did it in ten minutes in
> the old gevent-mysql code.
> See  github.com:smurfix/gevent-MySQL.git.
> 
> Looking at the ultramysql code, this would mean breaking up
> Connection::handleResultPacket(). If you create a new
> connection::readOneRow() instead, and call that from the resultset, that'd
> allow you to drop the m_capi.resultRowBegin/End() calls, so the whole thing
> would actually become (slightly) faster.
> 
> I hope to be able to get around to implementing that in a few weeks, I
> have a vacation coming up  if somebody beats me to it, good. ;-)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/esnme/ultramysql/issues/6

## 

## 

Jonas Trnstrm
Product Manager
 e-mail: jonas.tarnstrom@esn.me
 skype: full name "Jonas Trnstrm"
 phone: +46 (0)734 231 552

ESN Social Software AB
www.esn.me

**Comment by smurfix** [comment]
Hi,

Jonas Trnstrm:

> I definitly see your use case. The obvious solution would be to mimic the
> Cursor object used in other MySQL drivers (and in the official Python MySQL
> database protocol for that matter).
> 
> Well, there's no such thing as a cursor as far as MySQL is concerned.
> So sure, we can fake one, and attach the ResultSet to it, but it's still
> not really useful for anything. Except for slowing things down, of course,
> by adding another layer of indirection.

So I'd rather modify the interface as I outlined, and implement the DBD
frontend in an entirely separate glue layer.

> I'm sadly doubtful that I will have the time to implement in the near
> future.
> Good luck with your effort!
> 
> OK, we'll see what I can do. Shouldn't be too much of a problem really.

## 

-- Matthias Urlichs

**Comment by pubyun** [comment]
need this feature for huge table
