### ISSUE TITLE
Non existing db when connecting gives cryptic error

### ISSUE THREAD

**Issue by hrosenhorn** [esnme/ultramysql#9]
When connecting to a db and specifying a database that does not exist you get the error "SystemError: error return without exception set". Setting the db arg to a empty string is a work around.

Minimal example:

import unittest, umysql

class TestMySQL(unittest.TestCase):
    def testUnique(self):
        conn = umysql.Connection()
        conn.connect ('127.0.0.1', 3306, 'testuser', 'testuser', 'NO_EXISTING_DB')

```
    conn.close()
```

if **name** == '**main**':
    unittest.main()

**Comment by mkristo** [comment]
I get the same cryptic error message when using bad username/password combination.

**Comment by jskorpan** [comment]
Is this with monkey patched gevent sockets?

Den 27 februari 2012 11:32 skrev Hkan Rosenhorn <
reply@reply.github.com

> :
> 
> When connecting to a db and specifying a database that does not exist you
> get the error "SystemError: error return without exception set". Setting
> the db arg to a empty string is a work around.
> 
> Minimal example:
> 
> import unittest, umysql
> 
> class TestMySQL(unittest.TestCase):
>    def testUnique(self):
>        conn = umysql.Connection()
>        conn.connect ('127.0.0.1', 3306, 'testuser', 'testuser',
> 'NO_EXISTING_DB')
> 
> ```
>    conn.close()
> ```
> 
> if **name** == '**main**':
>    unittest.main()
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/esnme/ultramysql/issues/9

## 

## 

Jonas Trnstrm
Product Manager
 e-mail: jonas.tarnstrom@esn.me
 skype: full name "Jonas Trnstrm"
 phone: +46 (0)734 231 552

ESN Social Software AB
www.esn.me

**Comment by jskorpan** [comment]
Fixed, give proper SQLError
